### ISSUE TITLE
ERROR! locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by athosmoreno** [turicas/salarios-magistrados#2]
Tentei executar o script, porém todos os arquivos ficaram com o erro `unsupported locale setting` e o CSV do output ficou vazio.

Executei no Python 3.6 do Windows 10 e no Ubuntu 17.04 (no WSL) e o resultado foi o mesmo.

```
Extracting 29dbd9d3ec082188394449dbc564aa12.xls... ERROR! locale.Error: unsupported locale setting
Extracting d9657da5c5c430b044079bb2cb16eae2.xls... ERROR! locale.Error: unsupported locale setting
Extracting f2501340b64611e66224aeb45767eaf3.xls... ERROR! locale.Error: unsupported locale setting
Extracting bc506d094092730aee64ccb701212763.xls... ERROR! locale.Error: unsupported locale setting
Extracting f2d41244514643191ff6d45629b3855a.xls... ERROR! locale.Error: unsupported locale setting
Extracting d018d05e8bbcfe7e028207196b73ef89.xls... ERROR! locale.Error: unsupported locale setting
Extracting d55ef67a7c20e436fa1d6167698d80ab.xlsx... ERROR! AttributeError: 'PosixPath' object has no attribute 'seek'
Extracting 46ed9711a0fcd5f70292fc754855e65f.xls... ERROR! locale.Error: unsupported locale setting
Extracting 731778983576abbbdf37a2bf3cd4778d.xls... ERROR! locale.Error: unsupported locale setting
Extracting 858736c9622609245b1d0804f12dcca6.xls... ERROR! locale.Error: unsupported locale setting
Extracting 62d78b54747c7784ad0c69733dd1840f.xls... ERROR! locale.Error: unsupported locale setting
Extracting bec48e6e752fab72acaff674b658b782.xls... ERROR! locale.Error: unsupported locale setting
Extracting ce76b51ebf98eed08f71be75f4821fac.xls... ERROR! locale.Error: unsupported locale setting
Extracting e14eeae1fca5ca5bd18bf9b5f916fd87.xls... ERROR! locale.Error: unsupported locale setting
Extracting 34d32ee7a5856ed495229eff7598cdc8.xls... ERROR! locale.Error: unsupported locale setting
Extracting a87206d2e30bea3b98b5069637e23345.xls... ERROR! locale.Error: unsupported locale setting
Extracting 880b09da849f4a0c1cb129db6fa7d4d4.xls... ERROR! xlrd.biffh.XLRDError: Workbook is encrypted
Extracting 1e822641403083c6eea6aa6f0de8926c.xls... ERROR! locale.Error: unsupported locale setting
Extracting 7331383ae787372d4516f9a57e225b29.xls... ERROR! locale.Error: unsupported locale setting
Extracting 4bd6abae6161f3cff8ef22a6dfc75eb2.xls... ERROR! locale.Error: unsupported locale setting
Extracting e9c5203e1754365d32d0d54694b52f06.xls... ERROR! locale.Error: unsupported locale setting
Extracting 1430a6cc5e45e8f8aaf2005cffafe0e2.xls... ERROR! locale.Error: unsupported locale setting
Extracting 80a61ce4eabf38fbe244487b26cab618.xls... ERROR! locale.Error: unsupported locale setting
Extracting a1a46203a1e70463dff818be0d36dc42.xls... ERROR! locale.Error: unsupported locale setting
Extracting 2ef84d431d5458e277a808c24f97e131.xls... ERROR! locale.Error: unsupported locale setting
Extracting 807b3d6c5ff5fd82f6764185c9d70a05.xlsx... ERROR! AttributeError: 'PosixPath' object has no attribute 'seek'
Extracting 9b005d01801aeb8229fd2441f3fa0266.xls... ERROR! locale.Error: unsupported locale setting
Extracting cbbdf731cd71ba3cff033ccb11a40f53.xls... ERROR! locale.Error: unsupported locale setting
Extracting 6b51f50a8db991b2423f744c20241e58.xls... ERROR! locale.Error: unsupported locale setting
Extracting a210b7d9ad4cb93505c641fdec72eedf.xls... ERROR! locale.Error: unsupported locale setting
Extracting b3ba528d0792694f0ce73fedb2ac5a5b.xls... ERROR! locale.Error: unsupported locale setting
Extracting 76b0f4b6aed4c78f8d725c1d64547d27.xls... ERROR! locale.Error: unsupported locale setting
Extracting a5aa9d016d1c0d22f42c15a77d3d1167.xls... ERROR! locale.Error: unsupported locale setting
Extracting 537bc6a598497a28f1bba19bbe0be32c.xls... ERROR! locale.Error: unsupported locale setting
Extracting 1ca33e571e5797806b060e01bd5abb9f.xls... ERROR! locale.Error: unsupported locale setting
Extracting 5e822f30d79fe11007547ad9ca6d80e4.xls... ERROR! locale.Error: unsupported locale setting
Extracting 10fd1425f1f3fb34ebdfdff28abff802.xls... ERROR! locale.Error: unsupported locale setting
Extracting 1a16cf850bc7f356fc75b2610e6881da.xls... ERROR! locale.Error: unsupported locale setting
Extracting c5d6b706a418cfa2645820b9439f8df9.xls... ERROR! locale.Error: unsupported locale setting
Extracting 678d0c376d63872e42ceb30f25e436dc.xls... ERROR! locale.Error: unsupported locale setting
Extracting 555e727f51f9f4e168355093ea0ea63f.xls... ERROR! locale.Error: unsupported locale setting
Extracting 255932e6ae9eced3a25435aaf164caa0.xls... ERROR! locale.Error: unsupported locale setting
Extracting 6ea7db9193f0f499a772d1211ab8ee8d.xls... ERROR! locale.Error: unsupported locale setting
Extracting 9e1775c2a5033c3e1e94b3332b3e0309.xls... ERROR! locale.Error: unsupported locale setting
Extracting 55a9b27f8437ab27b71923ecfad52321.xls... ERROR! locale.Error: unsupported locale setting
Extracting 01ab246f5bf697d41dbb5db9678cca85.xls... ERROR! locale.Error: unsupported locale setting
Extracting e7bff9330e4034a33d15648d250a8ab4.xls... ERROR! locale.Error: unsupported locale setting
Extracting 17c4baad557fbf9c02f2126570e2d1e7.xlsx... ERROR! AttributeError: 'PosixPath' object has no attribute 'seek'
Extracting 8a16186e1ae5b46cd2279db1a784114f.xls... ERROR! locale.Error: unsupported locale setting
Extracting f1e38beec1e142e975f349b3b327e175.xls... ERROR! locale.Error: unsupported locale setting
Extracting 926598d64fb1a68718a346c7ecfda4bf.xls... ERROR! locale.Error: unsupported locale setting
Extracting 4a4b574f159cd7c3599bbe88defc5f93.xls... ERROR! locale.Error: unsupported locale setting
Extracting 0da5135dfa080e9753fb29b1adb224e6.xls... ERROR! locale.Error: unsupported locale setting
Extracting ea0e8c7a2c5950ff2d43a6c5b904db1b.xls... ERROR! locale.Error: unsupported locale setting
Extracting 5be125a2505f0a786e0d0ee2c761235a.xls... ERROR! locale.Error: unsupported locale setting
Extracting ccc9af81a772f9677664ba8930f6d793.xls... ERROR! locale.Error: unsupported locale setting
Extracting 76d75ed27dda34c0bf98b703316aa890.xls... ERROR! xlrd.biffh.XLRDError: Workbook is encrypted
Extracting 7e7e0f4cf7c02020b6ba87af4d72b7df.xls... ERROR! locale.Error: unsupported locale setting
Extracting 0f0106832fd80792b1f5d0e530deca71.xls... ERROR! locale.Error: unsupported locale setting
Extracting 584b48b8aa7557ee4715f9af11702b1f.xls... ERROR! locale.Error: unsupported locale setting
Extracting 405307b91e25735d1c904c28c7fe9278.xls... ERROR! locale.Error: unsupported locale setting
Extracting ea0b60b31ec7fdaf910bfc1ebbe67391.xls... ERROR! locale.Error: unsupported locale setting
Extracting 5919e4911f4b308a6828521384d77099.xls... ERROR! locale.Error: unsupported locale setting
Extracting c29feefebab8aa9b61cd1aa489299ecc.xls... ERROR! locale.Error: unsupported locale setting
Extracting 0c57450e62e30c13ddf67ce04a98009d.xls... ERROR! locale.Error: unsupported locale setting
Extracting 6693d4df7eca0afc01fbb3f4a4128b33.xls... ERROR! locale.Error: unsupported locale setting
Extracting 771fdf0733554ec4970802cd7167deb6.xls... ERROR! locale.Error: unsupported locale setting
Extracting 32dc6570569ce0b878874e322d206916.xls... ERROR! locale.Error: unsupported locale setting
Extracting e2770aee8bb3780f8b35e8254156967e.xls... ERROR! locale.Error: unsupported locale setting
Extracting e861cd842ca6b1d75aca6b8caa3ce039.xls... ERROR! locale.Error: unsupported locale setting
Extracting cfb6f3358660bd02aa89c815fe367069.xls... ERROR! locale.Error: unsupported locale setting
Extracting 7a0d51d24163565a87fba497958c9bf5.xls... ERROR! locale.Error: unsupported locale setting
Extracting 9fd2d3b23ef1b8042e895129f4029822.xls... ERROR! locale.Error: unsupported locale setting
Extracting 44d37e5d2efb352d343c20c9f6cb82b3.xls... ERROR! locale.Error: unsupported locale setting
Extracting b66895928f6b9bc054da290dd11c223c.xls... ERROR! locale.Error: unsupported locale setting
Extracting d87e4e887a7e5e20c8e82c4b0d21adfb.xls... ERROR! locale.Error: unsupported locale setting
Extracting 1f1ada0d9fdd4ed009ef65077ede7667.xls... ERROR! locale.Error: unsupported locale setting
Extracting bf2344e8ba4d261689b0bc8ca995769e.xls... ERROR! locale.Error: unsupported locale setting
Extracting a2484d14aa2c49b51a849fbb70e25723.xls... ERROR! locale.Error: unsupported locale setting
Extracting 95c42d31111ba11f6ae0db207c71b142.xls... ERROR! locale.Error: unsupported locale setting
Extracting 205177541f31dafc9516e7bb641dcb8d.xls... ERROR! locale.Error: unsupported locale setting
Extracting 10224bfa85ec6645b9bf2b7a34c15e6a.xls... ERROR! locale.Error: unsupported locale setting
Extracting 8e3419d6347bc3d61e7a877483edacd2.xls... ERROR! locale.Error: unsupported locale setting
Extracting 0b4d4aab97233da33e803a5ba889c5d5.xls... ERROR! locale.Error: unsupported locale setting
Extracting 1453eed57df8d257e5265a88be4f31b0.xls... ERROR! locale.Error: unsupported locale setting
Extracting result to output/salarios-magistrados-2017-12-20.csv...
Traceback (most recent call last):
  File "salarios_magistrados.py", line 196, in <module>
    main()
  File "salarios_magistrados.py", line 192, in main
    export_csv(result, output)
  File "salarios_magistrados.py", line 138, in export_csv
    writer = csv.DictWriter(fobj, fieldnames=data[0].keys())
IndexError: list index out of range
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "salarios_magistrados.py", line 196, in <module>
    main()
  File "salarios_magistrados.py", line 192, in main
    export_csv(result, output)
  File "salarios_magistrados.py", line 138, in export_csv
    writer = csv.DictWriter(fobj, fieldnames=data[0].keys())
IndexError: list index out of range
```

**Comment by turicas** [comment]
Não é bug no script. 

- Esse script não foi feito para ser rodado no Windows. Talvez funcione se você mudar no código o locale para "ptb" ou "ptb_bra" (em vez de "pt_BR.UTF-8"). 
- No Ubuntu você tem que instalar o locale pt_BR.UTF-8 para funcionar.

**Comment by athosmoreno** [comment]
Se o script "não foi feito pra rodar no Windows"(?), isso poderia ser colocado no README. De qualquer jeito, troquei o locale para `ptb_bra` e funcionou corretamente.

**Comment by turicas** [comment]
Eu não tenho Windows para testar e não tenho tempo para dar suporte ao Windows. Que tal fazer um pull request com essa alteração no README? Ou então você pode fazer um PR de forma que o código funcione tanto em Windows quanto em outros sistemas (bastaria definir o locale a partir de `sys.platform`).

**Comment by athosmoreno** [comment]
Pensei nisso também. Vou ver se faço e testo até hoje a noite.

**Comment by profjefer** [comment]
to usando ubuntu 19.3
LANG=pt_BR.UTF-8
requirements instalados sem erro
recebo esta mensgem também:
Extracting result to output/salarios-magistrados-2020-04-02.csv...
Traceback (most recent call last):
  File "salarios_magistrados.py", line 196, in <module>
    main()
  File "salarios_magistrados.py", line 192, in main
    export_csv(result, output)
  File "salarios_magistrados.py", line 138, in export_csv
    writer = csv.DictWriter(fobj, fieldnames=data[0].keys())
IndexError: list index out of range

**Comment by turicas** [comment]
O CNJ tirou do ar o site que tinha as planilhas. O script não vai mais funcionar.

**Comment by azromero** [comment]
Eles podem fazer isso? Não é obrigatório por lei divulgar?

Em sex., 3 de abr. de 2020 às 21:21, Álvaro Justen <notifications@github.com>
escreveu:

**Comment by turicas** [comment]
A LAI existe desde 2011 e nem sempre é cumprida.
Eles disponibilizaram os dados, porém em um painel horrível no QlikView: https://www.cnj.jus.br/transparencia-cnj/remuneracao-dos-magistrados/
Desse painel é muito mais complexo extrair as informações (já era ruim antes com as planilhas). Porém eles continuam recebendo as planilhas dos tribunais, poderiam consolidá-las e disponiblizar o resultado consolidado.

**Comment by profjefer** [comment]
> O CNJ tirou do ar o site que tinha as planilhas. O script não vai mais funcionar.

poxa :(

**Comment by turicas** [comment]
É do meu interesse que esse dataset continue funcionando, para atualizar lá no Brasil.IO. Estou em contato com eles tentando resolver.
