### ISSUE TITLE
Não executa os downloads

### ISSUE THREAD

**Issue by henriquenoliveira** [turicas/salarios-magistrados#20]
Bom dia!

Ao executar o 'scrapy runspider --loglevel=INFO -o data/output/planilha.csv download_files.py
gzip data/output/planilha.csv', aparece a seguinte mensagem:

(base) C:\Users\henri\Downloads\PythonScripts\Lerningwithcodes\Rows\salarios-magistrados-develop>scrapy runspider --loglevel=INFO -o data/output/planilha.csv download_files.py
2020-04-01 11:40:42 [scrapy.utils.log] INFO: Scrapy 2.0.1 started (bot: scrapybot)
2020-04-01 11:40:42 [scrapy.utils.log] INFO: Versions: lxml 4.5.0.0, libxml2 2.9.5, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 20.3.0, Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)], pyOpenSSL 19.0.0 (OpenSSL 1.1.1d  10 Sep 2019), cryptography 2.7, Platform Windows-10-10.0.18362-SP0
Traceback (most recent call last):
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\henri\AppData\Local\Continuum\anaconda3\Scripts\scrapy.exe\__main__.py", line 9, in <module>
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\cmdline.py", line 145, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\cmdline.py", line 99, in _run_print_help
    func(*a, **kw)
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\cmdline.py", line 153, in _run_command
    cmd.run(args, opts)
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\commands\runspider.py", line 79, in run
    module = _import_file(filename)
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\commands\runspider.py", line 21, in _import_file
    module = import_module(fname)
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\henri\Downloads\PythonScripts\Lerningwithcodes\Rows\salarios-magistrados-develop\download_files.py", line 17, in <module>
    settings.DOWNLOAD_PATH.mkdir()
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\pathlib.py", line 1258, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 3] O sistema não pode encontrar o caminho especificado: 'C:\\Users\\henri\\Downloads\\PythonScripts\\Lerningwithcodes\\Rows\\salarios-magistrados-develop\\data\\download'

E se eu crio o diretório \data\download manualmente ele aponta o seguinte erro ao executar o mesmo comando ou ao executar o 'python download_files.py':

(base) C:\Users\henri\Downloads\PythonScripts\Lerningwithcodes\Rows\salarios-magistrados-develop>scrapy runspider --loglevel=INFO -o data/output/planilha.csv download_files.py
2020-04-01 11:42:42 [scrapy.utils.log] INFO: Scrapy 2.0.1 started (bot: scrapybot)
2020-04-01 11:42:42 [scrapy.utils.log] INFO: Versions: lxml 4.5.0.0, libxml2 2.9.5, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 20.3.0, Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)], pyOpenSSL 19.0.0 (OpenSSL 1.1.1d  10 Sep 2019), cryptography 2.7, Platform Windows-10-10.0.18362-SP0
2020-04-01 11:42:43 [scrapy.crawler] INFO: Overridden settings:
{'FEED_FORMAT': 'csv',
 'FEED_URI': 'data/output/planilha.csv',
 'LOG_LEVEL': 'INFO',
 'SPIDER_LOADER_WARN_ONLY': True}
2020-04-01 11:42:43 [scrapy.extensions.telnet] INFO: Telnet Password: f08d1305d799891e
2020-04-01 11:42:43 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2020-04-01 11:42:43 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-04-01 11:42:43 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-04-01 11:42:43 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2020-04-01 11:42:43 [scrapy.core.engine] INFO: Spider opened
2020-04-01 11:42:43 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-04-01 11:42:43 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-04-01 11:42:44 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.cnj.jus.br/transparencia-cnj/remuneracao-dos-magistrados/> (referer: None)
Traceback (most recent call last):
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 117, in iter_errback
    yield next(it)
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\utils\python.py", line 345, in __next__
    return next(self.data)
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\utils\python.py", line 345, in __next__
    return next(self.data)
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 338, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\henri\appdata\local\continuum\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "C:\Users\henri\Downloads\PythonScripts\Lerningwithcodes\Rows\salarios-magistrados-develop\download_files.py", line 47, in parse
    update_message.split("enviaram os dados de")[1]
IndexError: list index out of range
2020-04-01 11:42:44 [scrapy.core.engine] INFO: Closing spider (finished)
2020-04-01 11:42:44 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 842,
 'downloader/request_count': 3,
 'downloader/request_method_count/GET': 3,
 'downloader/response_bytes': 25646,
 'downloader/response_count': 3,
 'downloader/response_status_count/200': 1,
 'downloader/response_status_count/301': 1,
 'downloader/response_status_count/302': 1,
 'elapsed_time_seconds': 1.519021,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 4, 1, 14, 42, 44, 596899),
 'log_count/ERROR': 1,
 'log_count/INFO': 10,
 'response_received_count': 1,
 'scheduler/dequeued': 3,
 'scheduler/dequeued/memory': 3,
 'scheduler/enqueued': 3,
 'scheduler/enqueued/memory': 3,
 'spider_exceptions/IndexError': 1,
 'start_time': datetime.datetime(2020, 4, 1, 14, 42, 43, 77878)}
2020-04-01 11:42:44 [scrapy.core.engine] INFO: Spider closed (finished)

Alguém pode me ajudar?

**Comment by turicas** [comment]
O site do CNJ está usando um dashboard horroroso e não libera mais as planilhas.
