### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by Andresigora** [turicas/salarios-magistrados#6]
O script está criando um csv vazio na pasta output

Traceback (most recent call last):
  File "salarios_magistrados.py", line 196, in <module>
    main()
  File "salarios_magistrados.py", line 192, in main
    export_csv(result, output)
  File "salarios_magistrados.py", line 138, in export_csv
    writer = csv.DictWriter(fobj, fieldnames=data[0].keys())
IndexError: list index out of range

**Comment by turicas** [comment]
Isso não é um erro do script. Provavelmente você esqueceu de instalar alguma dependência, está sem conexão à Internet ou está rodando no Windows (não foi feito pra isso, mas tem um pull request que resolve e em breve deve rodar).
